-- Existing game guest tokens remain valid; no Supabase Auth remapping.
CREATE SCHEMA IF NOT EXISTS dodge_private;
REVOKE ALL ON SCHEMA dodge_private FROM PUBLIC, anon, authenticated;
DO $$ BEGIN
 IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='dodge_writer') THEN
  CREATE ROLE dodge_writer NOLOGIN;
 END IF;
END $$;
GRANT USAGE ON SCHEMA dodge_private TO dodge_writer;
CREATE TABLE IF NOT EXISTS dodge_private.schema_version(
 singleton INTEGER PRIMARY KEY CHECK(singleton=1),version INTEGER NOT NULL);
INSERT INTO dodge_private.schema_version VALUES(1,1) ON CONFLICT(singleton) DO NOTHING;
CREATE TABLE IF NOT EXISTS dodge_private.guests (
                id TEXT PRIMARY KEY, token_hash TEXT UNIQUE NOT NULL,
                name TEXT NOT NULL, name_key TEXT UNIQUE NOT NULL,
                name_locked INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS dodge_private.friends (
                sender TEXT NOT NULL, recipient TEXT NOT NULL,
                accepted INTEGER NOT NULL DEFAULT 0,
                PRIMARY KEY(sender, recipient));
CREATE TABLE IF NOT EXISTS dodge_private.chat_unlocks(uid TEXT,feature TEXT,PRIMARY KEY(uid,feature));
CREATE TABLE IF NOT EXISTS dodge_private.chat_preferences(uid TEXT PRIMARY KEY,data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS dodge_private.chat_pairs(pair TEXT PRIMARY KEY,a TEXT,b TEXT,settings TEXT NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS dodge_private.chat_messages(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,pair TEXT,sender TEXT,nonce TEXT,kind TEXT,text TEXT,reply BIGINT,style INTEGER,created DOUBLE PRECISION,edited INTEGER DEFAULT 0,deleted INTEGER DEFAULT 0,seen DOUBLE PRECISION,delivered DOUBLE PRECISION,UNIQUE(sender,nonce));
CREATE TABLE IF NOT EXISTS dodge_private.chat_blocks(owner TEXT,target TEXT,PRIMARY KEY(owner,target));
CREATE TABLE IF NOT EXISTS dodge_private.chat_reactions(message BIGINT,uid TEXT,emoji TEXT,PRIMARY KEY(message,uid));
CREATE TABLE IF NOT EXISTS dodge_private.chat_media(id TEXT PRIMARY KEY,owner TEXT,kind TEXT,mime TEXT,data BYTEA,created DOUBLE PRECISION);
CREATE TABLE IF NOT EXISTS dodge_private.chat_reports(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,reporter TEXT,message BIGINT,reason TEXT,created DOUBLE PRECISION);
CREATE TABLE IF NOT EXISTS dodge_private.chat_days(pair TEXT,day TEXT,sender TEXT,PRIMARY KEY(pair,day,sender));
CREATE TABLE IF NOT EXISTS dodge_private.chat_events(id TEXT PRIMARY KEY,uid TEXT,kind TEXT,payload TEXT,created DOUBLE PRECISION,sent INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS dodge_private.push_devices(uid TEXT,token TEXT UNIQUE,PRIMARY KEY(uid,token));
CREATE TABLE IF NOT EXISTS dodge_private.meta (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL
        );
CREATE TABLE IF NOT EXISTS dodge_private.scores (
            uid TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            score INTEGER NOT NULL DEFAULT 0,
            rank TEXT NOT NULL DEFAULT '-',
            rank_index INTEGER NOT NULL DEFAULT -1,
            updated_at TEXT NOT NULL
        );
CREATE TABLE IF NOT EXISTS dodge_private.monthly_rewards (
            month TEXT NOT NULL,
            uid TEXT NOT NULL,
            name TEXT NOT NULL,
            place INTEGER NOT NULL,
            reward INTEGER NOT NULL,
            claimed INTEGER NOT NULL DEFAULT 0,
            PRIMARY KEY (month, uid)
        );
CREATE INDEX IF NOT EXISTS chat_messages_pair ON dodge_private.chat_messages(pair,id);
CREATE INDEX IF NOT EXISTS friends_recipient_accepted ON dodge_private.friends(recipient,accepted);
CREATE INDEX IF NOT EXISTS chat_messages_sender_created ON dodge_private.chat_messages(sender,created);
CREATE INDEX IF NOT EXISTS chat_messages_text_kind ON dodge_private.chat_messages(text,kind);
CREATE INDEX IF NOT EXISTS chat_media_owner_created ON dodge_private.chat_media(owner,created);
CREATE INDEX IF NOT EXISTS chat_reports_reporter_created ON dodge_private.chat_reports(reporter,created);
CREATE INDEX IF NOT EXISTS chat_days_pair_day ON dodge_private.chat_days(pair,day);
CREATE INDEX IF NOT EXISTS chat_events_sent_created ON dodge_private.chat_events(sent,created);
CREATE INDEX IF NOT EXISTS push_devices_uid ON dodge_private.push_devices(uid);
ALTER TABLE dodge_private.guests ENABLE ROW LEVEL SECURITY;
CREATE POLICY server_access ON dodge_private.guests TO dodge_writer USING(true) WITH CHECK(true);
ALTER TABLE dodge_private.friends ENABLE ROW LEVEL SECURITY;
CREATE POLICY server_access ON dodge_private.friends TO dodge_writer USING(true) WITH CHECK(true);
ALTER TABLE dodge_private.chat_unlocks ENABLE ROW LEVEL SECURITY;
CREATE POLICY server_access ON dodge_private.chat_unlocks TO dodge_writer USING(true) WITH CHECK(true);
ALTER TABLE dodge_private.chat_preferences ENABLE ROW LEVEL SECURITY;
CREATE POLICY server_access ON dodge_private.chat_preferences TO dodge_writer USING(true) WITH CHECK(true);
ALTER TABLE dodge_private.chat_pairs ENABLE ROW LEVEL SECURITY;
CREATE POLICY server_access ON dodge_private.chat_pairs TO dodge_writer USING(true) WITH CHECK(true);
ALTER TABLE dodge_private.chat_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY server_access ON dodge_private.chat_messages TO dodge_writer USING(true) WITH CHECK(true);
ALTER TABLE dodge_private.chat_blocks ENABLE ROW LEVEL SECURITY;
CREATE POLICY server_access ON dodge_private.chat_blocks TO dodge_writer USING(true) WITH CHECK(true);
ALTER TABLE dodge_private.chat_reactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY server_access ON dodge_private.chat_reactions TO dodge_writer USING(true) WITH CHECK(true);
ALTER TABLE dodge_private.chat_media ENABLE ROW LEVEL SECURITY;
CREATE POLICY server_access ON dodge_private.chat_media TO dodge_writer USING(true) WITH CHECK(true);
ALTER TABLE dodge_private.chat_reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY server_access ON dodge_private.chat_reports TO dodge_writer USING(true) WITH CHECK(true);
ALTER TABLE dodge_private.chat_days ENABLE ROW LEVEL SECURITY;
CREATE POLICY server_access ON dodge_private.chat_days TO dodge_writer USING(true) WITH CHECK(true);
ALTER TABLE dodge_private.chat_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY server_access ON dodge_private.chat_events TO dodge_writer USING(true) WITH CHECK(true);
ALTER TABLE dodge_private.push_devices ENABLE ROW LEVEL SECURITY;
CREATE POLICY server_access ON dodge_private.push_devices TO dodge_writer USING(true) WITH CHECK(true);
ALTER TABLE dodge_private.meta ENABLE ROW LEVEL SECURITY;
CREATE POLICY server_access ON dodge_private.meta TO dodge_writer USING(true) WITH CHECK(true);
ALTER TABLE dodge_private.scores ENABLE ROW LEVEL SECURITY;
CREATE POLICY server_access ON dodge_private.scores TO dodge_writer USING(true) WITH CHECK(true);
ALTER TABLE dodge_private.monthly_rewards ENABLE ROW LEVEL SECURITY;
CREATE POLICY server_access ON dodge_private.monthly_rewards TO dodge_writer USING(true) WITH CHECK(true);
ALTER TABLE dodge_private.schema_version ENABLE ROW LEVEL SECURITY;
CREATE POLICY server_access ON dodge_private.schema_version TO dodge_writer USING(true) WITH CHECK(true);
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA dodge_private TO dodge_writer;
REVOKE INSERT,UPDATE,DELETE ON dodge_private.schema_version FROM dodge_writer;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA dodge_private TO dodge_writer;
REVOKE ALL ON ALL TABLES IN SCHEMA dodge_private FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA dodge_private FROM PUBLIC, anon, authenticated;
